### ISSUE TITLE
Load user module order

### ISSUE THREAD

**Issue by hieutd1** [mage/mage#269]
I got a bug when require my module:
Have 3 modules with order:
+chat
+mysql
+user

chat and user require mysql bolt, user use mysql normal but chat got a null
![image](https://user-images.githubusercontent.com/10185037/50131972-4b78f600-02b7-11e9-9829-081c8104bb7e.png)

**Comment by stelcheck** [comment]
Yes, that is the issue.

`useApplicationModules` doesn't figure out your dependencies. In the past, we would specify the list of dependencies manually, and make sure we don't forget to add them (and make sure to keep them in the right order).

As you can imagine, this is terribly prone to error :) 

The solution is simple: instead of accessing modules from the `mage` root object, simply require/import them directly:

```
const mysql = require(`../mysql`)
```

This way you will always load the dependency correctly - and as a bonus it deals with most circular dependency cases.

**Comment by hieutd1** [comment]
thanks for your support!
