### ISSUE TITLE
Uncaught exception with dockerized Couchbase

### ISSUE THREAD

**Issue by ronkorving** [mage/mage#72]
When booting up a docker container running Couchbase *right* before running `npm run archivist-create` (without waiting for the container to be up), the follow uncaught exception occurs:

```
Creating redacted-zookeeper-local_1
Creating redacted-couchbase-local_1
m-8800 - 11:21:01.106     <debug> [MAGE archivist] Creating persistent vaults ["volatileVault","userVault"]
m-8800 - 11:21:01.110     <debug> [MAGE archivist vault:volatileVault] Setting up couchbase vault, using flagStyle node-memcached
m-8800 - 11:21:01.113     <debug> [MAGE archivist vault:userVault] Setting up couchbase vault, using flagStyle node-memcached
m-8800 - 11:21:01.130 <emergency> [MAGE processManager] Uncaught exception: socket hang up
  data: {
    "code": "ECONNRESET",
    "file": "_http_client.js",
    "line": 302,
    "offset": 15,
    "type": "Error",
    "stack": [
      "createHangUpError (_http_client.js:302:15)",
      "Socket.socketOnEnd (_http_client.js:394:23)",
      "emitNone (events.js:91:20)",
      "Socket.emit (events.js:188:7)",
      "endReadableNT (_stream_readable.js:975:12)",
      "_combinedTickCallback (internal/process/next_tick.js:80:11)",
      "process._tickCallback (internal/process/next_tick.js:104:9)"
    ]
  }
```

Our vault should really enter a reconnect loop. Whether this is uncaught because of the couchbase module, or because of the vault will have to be investigated.

**Comment by stelcheck** [comment]
Thinking about this one, this behavior would go counter to the behavior of most other systems in MAGE; for instance, failure to connect to service discovery at start time (with similar errors) would cause the same kind of crash. 

In short, this would mean that we may be bringing in a feature that would now behave differently than others (same would likely be true for other vaults migration).

Alternatively perhaps, what we *could* do is, add something that runs before each vault migrations regardless of service; we could simply attempt a TCP connection, and once it succeeds, disconnect and proceed.  This would solve the issue potentially for all vault migrations at once (although I do not know if the proper data would be present for a higher level to provide such functionality).

**Comment by ronkorving** [comment]
Service discovery connection failure is not fatal, is it? In any case, it's worth considering how we treat unresponsive services we depend on. Retry-loop? If so, for how long? At some point, if the app cannot function as intended, I guess it should be fatal.

The real potential issue behind this particular GitHub issue though, is that I *suspect* the `couchbase` module makes this uncatchable, which means we won't even have a say in how MAGE deals with it. If that is the case, that would be problematic to me and the `couchbase` module would deserve a patch.

**Comment by stelcheck** [comment]
The main issue here is that you are going through the Docker proxy - which basically sits on the port and purposefully (?!?!) ECONNRESET everything until it detects the real remote port being up.

Which can lead to some hilarious (sort of?) issues. See https://github.com/Microsoft/vscode/issues/26348 for more details.

So this one is a tough one to crack, because it really is Docker getting in your way - not Couchbase. To be more precise, the fact that you run your MAGE server outside of Docker while everything else is in Docker is the main cause of your trouble here.

The way I see it, you have two options:

  1. Run your app server in Docker. It is not without its pains, but you do avoid a large class of issues by respecting the Docker way.

  2. Write a project-specific utility script or external module which will try to TCP connects to a given port until you no longer get ECONNRESET, then proceed with your archivist related commands.

Either way, this specific issue really isn't something I believe ought to be fixed in MAGE itself, since it really seems to be a problem specifically tied up to a single architectural structure... but feel free to correct me if you believe I am wrong.

**Comment by ronkorving** [comment]
No, I think that's pretty much it :-/ I'll close this issue.
